import { ms } from 'react-native-size-matters';
import { sfs } from '../../utils/responsibleText';

export default {
  Sizes: {
    FONTSIZE_BUTTON: sfs(8),
    FONTSIZE_BUTTON_SEND: sfs(12),
    FONTSIZE_BUTTON_TITLE: sfs(20),
    ICON_SIZE_BUTTON: sfs(15),
    FONTSIZE_TITLE: sfs(22),
    FONTSIZE_LABEL: sfs(12),
    FONTSIZE_INPUT_LABEL: sfs(13),
    FONTSIZE_INPUT: sfs(20),
    ICON_SIZE: ms(22),
    FONTSIZE_SUBTITLE: sfs(12),
  },

  Colors: {
    BLACK: '#000',
    WHITE: '#FFF',
    GRAY: '#333',
    FONT_INPUT: '#444444',
    MEDIUM_GRAY: '#666',
    LIGHT_GRAY: '#EEE',
    GRANITE: '#c8c9c7',
    ERROR: '#C12126',
    FEEDBACK_CORRECT: '#6ea204',
    FEEDBACK_WARNING: '#F2AF00',
    BACKGROUND_WHITE: '#fafafa',
    GRAY_LIGHT: '#bbbbbb',
    SECONDARY_LIGHT_GRAY: '#b4b4b4',
    CARD_TEXT: '#707070',
    BORDER_BLACK: '#0000001A',
    SECONDARY_MEDIUM_GRAY: '#848484',
    COLOR_APLICATION: '#121212',
    SOFT_BLACK: '#161616',
    GREY: '#C2C2C2',
    SOFT_GREY: '#F6F6F6',
    PINK: '#FA81AC',
    PURPLE: '#5D5B7E',
    DARK_PURPLE: '#34325E',
    BACKGROUND: '#121212',
    BORDER: '#FFFF00',
    BUTTON_TEXT: '#FFFF00',
    DEFAULT_FONT: '#FFFF00',
    BUTTON_BACKGROUND: '#121212',
    SUBTITLE: '#C8C9C7',
    TITLE_FONT: '#FFF',
    FONT_HOME: '#FFF',
    INPUT_COLOR: '#FFF',
    BORDER_PROFILE: '#FFFF00',
    BACKGROUND_INPUT: '#1a1a1a',
    BORDER_SEARCH: '#FFFF00',
    BACKGROUND_MODAL: '#000',
    TEXT_CLICKABLE: '#FFFF00',
    BUTTON_CANCEL: '#FFFF00',
    SHOW_BUTTON: '#FFFF00',
    BUTTON_COLOR: '#f57b5d',
  },
};
